---
obsidian_livesync_couchdb_settings:
  - section: "chttpd"
    key: "require_valid_user"
    value: "true"
  - section: "chttpd_auth"
    key: "require_valid_user"
    value: "true"
  - section: "httpd"
    key: "WWW-Authenticate"
    value: 'Basic realm="couchdb"'
  - section: "httpd"
    key: "enable_cors"
    value: "true"
  - section: "chttpd"
    key: "enable_cors"
    value: "true"
  - section: "chttpd"
    key: "max_http_request_size"
    value: "4294967296"
  - section: "chttpd"
    key: "bind_address"
    value: "0.0.0.0"
  - section: "couchdb"
    key: "max_document_size"
    value: "50000000"
  - section: "cors"
    key: "credentials"
    value: "true"
  - section: "cors"
    key: "origins"
    value: "app://obsidian.md,capacitor://localhost,http://localhost"
