---
# =============================================================================
# Security Hardening Tasks - Part 1 of the Guide
# =============================================================================

- name: Include SSH hardening tasks
  ansible.builtin.include_tasks: ssh_hardening.yml
  tags: ["ssh"]

- name: Include firewall configuration tasks
  ansible.builtin.include_tasks: firewall.yml
  tags: ["firewall"]

- name: Include fail2ban setup tasks
  ansible.builtin.include_tasks: fail2ban.yml
  tags: ["fail2ban"]

- name: Include system updates tasks
  ansible.builtin.include_tasks: system_updates.yml
  tags: ["updates"]
